### ISSUE TITLE
Switch Rooms, CLI no longer works.

### ISSUE THREAD

**Issue by Izzmo** [Izzmo/TTEnhanced#28]
If you switch a room (not by typing in the URL bar), then the CLI no longer works because it's room object and turntable object references are pointing to old objects no longer connected to the active socket connection.

**Comment by hink** [comment]
https://github.com/Frick/ttplus/blob/master/scripts/onPage.js#L228

Will use something like this to detect room change.

**Comment by Izzmo** [comment]
Sounds good.
