### ISSUE TITLE
Live Stats

### ISSUE THREAD

**Issue by Izzmo** [Izzmo/TTEnhanced#7]
Add the ability to see live vote casting, join/leaves, and snags in the chat (or some other place for viewing).

**Comment by Izzmo** [comment]
I was thinking about this, streamlining it in some way. What do you think about just associated icons with each action and just showing the icon somewhere and then on rollover it will expand to say who did what?

Also, like chat, as each action item pops up, it will scroll up, possibly fade in some way when the list gets too big.

Thoughts?

**Comment by hink** [comment]
I'd like to know when and at what time. It's going to be spammy, but you can turn it off and on.

**Comment by Izzmo** [comment]
Up to you, we can put it in another pane too.
